services:
  - type: web
    name: vyamir-app
    runtime: docker
    plan: free
    envVars:
      - key: PEXELS_API_KEY
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
