services:
  - type: web
    name: vyamir
    env: python
    buildCommand: bash build.sh
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: NODE_VERSION
        value: 18.17.1
      - key: FIREBASE_API_KEY
        sync: false
      - key: PEXELS_API_KEY
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
